"""Print profiles: Bambu Studio vocabulary in, PrusaSlicer .ini out."""
from __future__ import annotations

import hashlib
import json

# Bambu Studio system defaults per nozzle (read from bambulab/BambuStudio profile JSONs).
BAMBU_DEFAULTS = {
    0.4: {
        "layer_height": 0.20, "first_layer_height": 0.20,
        "walls": 2, "top": 5, "bottom": 3, "top_min_thickness": 1.0, "bottom_min_thickness": 0.0,
        "infill": 15, "pattern": "cubic",
        "line_widths": {"outer": 0.42, "inner": 0.45, "infill": 0.45, "solid": 0.42, "top": 0.42, "first": 0.50},
        "infill_wall_overlap": 15, "one_wall_top": True, "min_sparse_area": 15.0, "thin_walls": False,
        "gap_fill": True, "infill_direction": 45,
    },
    0.6: {
        "layer_height": 0.30, "first_layer_height": 0.30,
        "walls": 2, "top": 3, "bottom": 3, "top_min_thickness": 0.8, "bottom_min_thickness": 0.0,
        "infill": 15, "pattern": "cubic",
        "line_widths": {"outer": 0.62, "inner": 0.62, "infill": 0.62, "solid": 0.62, "top": 0.62, "first": 0.62},
        "infill_wall_overlap": 15, "one_wall_top": True, "min_sparse_area": 15.0, "thin_walls": False,
        "gap_fill": True, "infill_direction": 45,
    },
}

PATTERNS = ["cubic", "grid", "gyroid", "triangles", "rectilinear", "honeycomb", "3dhoneycomb", "adaptivecubic",
            "supportcubic", "lightning", "alignedrectilinear", "stars", "concentric"]

# Bambu pattern name -> PrusaSlicer fill_pattern
PATTERN_MAP = {p: p for p in PATTERNS}
PATTERN_MAP.update({"zig-zag": "rectilinear", "line": "alignedrectilinear", "tri-hexagon": "stars"})


def default_params(nozzle: float = 0.4) -> dict:
    base = BAMBU_DEFAULTS.get(float(nozzle), BAMBU_DEFAULTS[0.4])
    p = json.loads(json.dumps(base))
    p["nozzle"] = float(nozzle)
    return p


def normalize(params: dict) -> dict:
    """Fill gaps from the nozzle default and coerce types."""
    nozzle = float(params.get("nozzle", 0.4))
    p = default_params(nozzle)
    for k, v in params.items():
        if k == "line_widths" and isinstance(v, dict):
            p["line_widths"].update({kk: float(vv) for kk, vv in v.items()})
        elif v is not None:
            p[k] = v
    for k in ("layer_height", "first_layer_height", "top_min_thickness", "bottom_min_thickness", "infill", "min_sparse_area"):
        p[k] = float(p[k])
    for k in ("walls", "top", "bottom"):
        p[k] = int(round(float(p[k])))
    p["infill"] = max(0.0, min(100.0, p["infill"]))
    p["one_wall_top"] = bool(p.get("one_wall_top", True))
    return p


def effective_shell_layers(params: dict) -> tuple[int, int]:
    """Bambu's 'whichever is more' rule for top/bottom layer counts."""
    import math
    lh = params["layer_height"]
    top = max(params["top"], math.ceil(params["top_min_thickness"] / lh - 1e-9) if params["top_min_thickness"] > 0 else 0)
    bot = max(params["bottom"], math.ceil(params["bottom_min_thickness"] / lh - 1e-9) if params["bottom_min_thickness"] > 0 else 0)
    return top, bot


def profile_string(params: dict) -> str:
    p = normalize(params)
    inf = f"{p['infill']:g}%"
    pat = "" if p["infill"] >= 100 else f" {p['pattern']}"
    s = f"{p['walls']}W · {p['top']}T/{p['bottom']}B · {inf}{pat} · {p['layer_height']:g}"
    if abs(p["nozzle"] - 0.4) > 1e-6:
        s += f" · {p['nozzle']:g}"
    return s


def profile_hash(params: dict, filament: dict | None = None) -> str:
    p = normalize(params)
    key = {"p": p}
    if filament:
        key["f"] = {"density": round(float(filament["density"]), 4), "flow": round(float(filament.get("flow", 1.0)), 4)}
    return hashlib.sha1(json.dumps(key, sort_keys=True).encode()).hexdigest()[:16]


def _ver_tuple(version: str | None) -> tuple:
    if not version:
        return (2, 9, 0)
    import re
    m = re.findall(r"\d+", version)
    return tuple(int(x) for x in m[:3]) if m else (2, 9, 0)


def to_prusa_ini(params: dict, filament: dict, slicer_version: str | None = None, bed=(400, 400)) -> str:
    """Generate a PrusaSlicer print+filament+printer config reproducing Bambu Studio's behaviour."""
    p = normalize(params)
    v = _ver_tuple(slicer_version)
    lw = p["line_widths"]
    density = float(filament["density"])
    flow = float(filament.get("flow", 1.0) or 1.0)
    lines = [
        "# generated by SliceBudget",
        f"layer_height = {p['layer_height']:g}",
        f"first_layer_height = {p['first_layer_height']:g}",
        f"perimeters = {p['walls']}",
        f"top_solid_layers = {p['top']}",
        f"bottom_solid_layers = {p['bottom']}",
        f"top_solid_min_thickness = {p['top_min_thickness']:g}",
        f"bottom_solid_min_thickness = {p['bottom_min_thickness']:g}",
        f"fill_density = {p['infill']:g}%",
        f"fill_pattern = {'rectilinear' if p['infill'] >= 100 else PATTERN_MAP.get(p['pattern'], 'cubic')}",
        f"fill_angle = {p.get('infill_direction', 45)}",
        "top_fill_pattern = monotonic",
        "bottom_fill_pattern = monotonic",
        f"extrusion_width = {lw['inner']:g}",
        f"external_perimeter_extrusion_width = {lw['outer']:g}",
        f"perimeter_extrusion_width = {lw['inner']:g}",
        f"infill_extrusion_width = {lw['infill']:g}",
        f"solid_infill_extrusion_width = {lw['solid']:g}",
        f"top_infill_extrusion_width = {lw['top']:g}",
        f"first_layer_extrusion_width = {lw['first']:g}",
        f"infill_overlap = {p['infill_wall_overlap']:g}%",
        f"solid_infill_below_area = {p.get('min_sparse_area', 15):g}",
        f"thin_walls = {1 if p.get('thin_walls') else 0}",
        f"gap_fill_enabled = {1 if p.get('gap_fill', True) else 0}",
        "perimeter_generator = classic",
        "extra_perimeters = 0",
        "extra_perimeters_on_overhangs = 0",
        "infill_every_layers = 1",
        "infill_anchor = 400%",
        "infill_anchor_max = 20",
        "seam_position = aligned",
        "support_material = 0",
        "support_material_auto = 0",
        "skirts = 0",
        "brim_width = 0",
        "brim_type = no_brim",
        "raft_layers = 0",
        "elefant_foot_compensation = 0",
        "complete_objects = 0",
        "wipe_tower = 0",
        # filament
        f"filament_density = {density:g}",
        f"extrusion_multiplier = {flow:g}",
        "filament_diameter = 1.75",
        "filament_cost = 0",
        # printer
        f"nozzle_diameter = {p['nozzle']:g}",
        f"bed_shape = 0x0,{bed[0]}x0,{bed[0]}x{bed[1]},0x{bed[1]}",
        "max_print_height = 400",
        "printer_technology = FFF",
        "gcode_flavor = marlin2",
        "use_relative_e_distances = 0",
        "retract_length = 0",
        "start_gcode = ",
        "end_gcode = ",
        "layer_gcode = ",
        "before_layer_gcode = ",
        "toolchange_gcode = ",
        "gcode_comments = 0",
        "gcode_label_objects = disabled",
        "binary_gcode = 0",
    ]
    if v < (2, 8, 0):
        lines = [l for l in lines if not l.startswith("binary_gcode")]
    if v >= (2, 8, 0):
        lines.append("ensure_vertical_shell_thickness = enabled")
        lines.append(f"top_one_perimeter_type = {'top' if p['one_wall_top'] else 'none'}")
    else:
        lines.append("ensure_vertical_shell_thickness = 1")
    return "\n".join(lines) + "\n"


def to_bambu_preset(params: dict, name: str, printer_name: str = "Bambu Lab P1S", inherits: str | None = None) -> dict:
    """A Bambu Studio user process preset (JSON) that overrides only what differs from the system default."""
    p = normalize(params)
    base = default_params(p["nozzle"])
    nozzle = p["nozzle"]
    if inherits is None:
        inherits = f"{'0.20mm Standard' if nozzle == 0.4 else '0.30mm Standard'} @BBL {printer_name.replace('Bambu Lab ', '')}{'' if nozzle == 0.4 else ' 0.6 nozzle'}"
    out = {
        "type": "process", "name": name, "from": "User", "inherits": inherits, "version": "1.9.0.0",
        "wall_loops": str(p["walls"]), "top_shell_layers": str(p["top"]), "bottom_shell_layers": str(p["bottom"]),
        "top_shell_thickness": f"{p['top_min_thickness']:g}", "bottom_shell_thickness": f"{p['bottom_min_thickness']:g}",
        "sparse_infill_density": f"{p['infill']:g}%", "sparse_infill_pattern": p["pattern"],
        "layer_height": f"{p['layer_height']:g}", "initial_layer_print_height": f"{p['first_layer_height']:g}",
        "infill_wall_overlap": f"{p['infill_wall_overlap']:g}%", "only_one_wall_top": "1" if p["one_wall_top"] else "0",
        "minimum_sparse_infill_area": f"{p.get('min_sparse_area', 15):g}",
    }
    lw = p["line_widths"]; blw = base["line_widths"]
    keys = {"outer": "outer_wall_line_width", "inner": "inner_wall_line_width", "infill": "sparse_infill_line_width",
            "solid": "internal_solid_infill_line_width", "top": "top_surface_line_width", "first": "initial_layer_line_width"}
    for k, bk in keys.items():
        if abs(lw[k] - blw[k]) > 1e-6:
            out[bk] = f"{lw[k]:g}"
    return out
